### ISSUE TITLE
If there is a space at the beginning of a line, the format of the plug-in conversion will be incorrect

### ISSUE THREAD

**Issue by jiajiala** [lilian-pouliquen/obsidian-custom-list-character#1]
If there is a space at the beginning of a line, the format of the plug-in conversion will be incorrect
And it's hard to detect
![image](https://github.com/lilian-pouliquen/obsidian-custom-list-character/assets/73203026/8455669b-fca7-4f91-b010-e8bae79b75f4)

**Comment by lilian-pouliquen** [comment]
Hello @jiajiala!
Thanks for reporting your issue.
Can you detail a bit more what would you expect?
Can you write your example in code fences here? so that I can test it and understand better the behaviour
I'll try my best to correct it!

**Comment by jiajiala** [comment]
![Honeycam 2023-11-27 21-47-40](https://github.com/lilian-pouliquen/obsidian-custom-list-character/assets/73203026/b27830b6-c06a-4c21-84d1-bfd4eae909c8)
As shown in the figure, once a line starts with a space, it will be misformatted when converted to a list

The expected result is that whitespace is ignored and a format like the second line is generated
`  aaa
- aaa`

**Comment by lilian-pouliquen** [comment]
Okay I see thanks!
Actually, this is the expected behaviour: I wanted the indentation to be kept while formatting and unformatting the selection.
I'll work on a new setting to choose weither or not the user want to trim the selection, if that suits you needs
